// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBgcCbxRmxVE3GapweLIfiBT9zo5LPcyU',
    appId: '1:780792946688:web:4b0edc60090e724d30f8e5',
    messagingSenderId: '780792946688',
    projectId: 'rdms-mukalla',
    authDomain: 'rdms-mukalla.firebaseapp.com',
    databaseURL: 'https://rdms-mukalla-default-rtdb.firebaseio.com',
    storageBucket: 'rdms-mukalla.firebasestorage.app',
    measurementId: 'G-0YZCZTN0T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW7c37jnyardXRB-PaiGajNfHWZ7FcLNk',
    appId: '1:780792946688:android:e7c6c2231da8732630f8e5',
    messagingSenderId: '780792946688',
    projectId: 'rdms-mukalla',
    databaseURL: 'https://rdms-mukalla-default-rtdb.firebaseio.com',
    storageBucket: 'rdms-mukalla.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGjpcVDJbM81KkAudK9J7yr54waTdShi8',
    appId: '1:780792946688:ios:e977090e8a670b7c30f8e5',
    messagingSenderId: '780792946688',
    projectId: 'rdms-mukalla',
    databaseURL: 'https://rdms-mukalla-default-rtdb.firebaseio.com',
    storageBucket: 'rdms-mukalla.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGjpcVDJbM81KkAudK9J7yr54waTdShi8',
    appId: '1:780792946688:ios:e977090e8a670b7c30f8e5',
    messagingSenderId: '780792946688',
    projectId: 'rdms-mukalla',
    databaseURL: 'https://rdms-mukalla-default-rtdb.firebaseio.com',
    storageBucket: 'rdms-mukalla.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBgcCbxRmxVE3GapweLIfiBT9zo5LPcyU',
    appId: '1:780792946688:web:884d54137422250430f8e5',
    messagingSenderId: '780792946688',
    projectId: 'rdms-mukalla',
    authDomain: 'rdms-mukalla.firebaseapp.com',
    databaseURL: 'https://rdms-mukalla-default-rtdb.firebaseio.com',
    storageBucket: 'rdms-mukalla.firebasestorage.app',
    measurementId: 'G-6XKVK88PSM',
  );
}
